Add condition to handle tidy returning 1, which is only warning and no errors

diff --git a/.github/workflows/tidy_html5.yml b/.github/workflows/tidy_html5.yml
--- a/.github/workflows/tidy_html5.yml
+++ b/.github/workflows/tidy_html5.yml
@@ -13,5 +13,7 @@ jobs:
       - run: sudo apt install tidy
 
       - name: Check all HTML files
-        run: tidy -config tidy_config.txt *.html
+        run: |
+          tidy -config tidy.config *.html
+          test $? -lt 2 || echo "Errors founds"
 
